apiVersion: v1
kind: Service
metadata:
  name: drage
  namespace: staging
spec:
  type: LoadBalancer  # Change the service type to LoadBalancer
  ports:
  - name: api
    port: 80
    targetPort: 27017
  selector:
    app: nodeapp

